language: objective-c
osx_image: xcode9

xcode_workspace: UICollectionViewEmptyState.xcworkspace
xcode_scheme: Tests

cache:
  - bundler
  - cocoapods

before_install:
  - gem install bundler
  - bundle install
  - pod repo update
  - pod install

script:
  - xcodebuild -workspace UICollectionViewEmptyState.xcworkspace -scheme Demo -destination 'platform=iOS Simulator,name=iPad Air,OS=10.3.1' build | xcpretty
  - xcodebuild -workspace UICollectionViewEmptyState.xcworkspace -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3.1' test | xcpretty
  - xcodebuild -workspace UICollectionViewEmptyState.xcworkspace -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0.0' test | xcpretty
